### ISSUE TITLE
【Feature Request】希望支持读取 txt 文件进行下载

### ISSUE THREAD

**Issue by MuelNova** [silentEAG/voiceload#1]
- [x]  我已仔细阅读并了解上述注意事项
- [x] 我已使用最新版本测试过，确认功能并未实现
- [x] 我确定在 [GitHub Issues](https://github.com/silentEAG/voiceload/issue) 中没有相同或相似的需求
- [ ] 我有足够的时间和能力，愿意为此提交 PR 来实现功能

**为什么需要这个功能**
目前版本下， voiceload 对于大量音频的下载支持较弱，无法满足大量爬取的需求

**实现的功能是什么样的**
通过增加对 Option 的支持，增加一个指定文件的功能。通过指定文件路径，可以自动读取该文件下的每一行的视频 BV 号

**其它**
可以尝试增加 AV 号以及链接（包括短链接）的支持，以提高泛用性。

**Comment by silentEAG** [comment]
好特性，已加入List 505fbb4e70055983acae32b5c67b743728884680

**Comment by silentEAG** [comment]
Closed
